<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Resources/haru.ico</ApplicationIcon>
    <!-- 필요하면 여기 Name/RootNamespace 등을 HyIO로 명시해도 됨 -->
    <!-- <RootNamespace>HyIO</RootNamespace> -->
    <!-- <AssemblyName>HyIO</AssemblyName> -->
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\**\*.*" />
    <Resource Include="Fonts\ONE_Mobile_POP.ttf" />
  </ItemGroup>

</Project>
